# Generated by Django 5.2.17 on 2026-08-16 12:18

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "poll_interval_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[django.core.validators.MinValueValidator(60)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SMTPConfig",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255)),
                ("port", models.PositiveIntegerField(default=465)),
                (
                    "security",
                    models.CharField(
                        choices=[("ssl", "SSL/TLS"), ("starttls", "STARTTLS")],
                        default="ssl",
                        max_length=16,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=255)),
                ("from_email", models.EmailField(blank=True, max_length=254)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("encrypted_password", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MonitorTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_url", models.URLField(max_length=1000)),
                ("normalized_url", models.URLField(max_length=1000)),
                ("query_key", models.CharField(db_index=True, max_length=128)),
                ("city_id", models.PositiveIntegerField()),
                ("city_name", models.CharField(max_length=80)),
                ("movie_id", models.CharField(max_length=32)),
                ("movie_name", models.CharField(max_length=200)),
                ("show_date", models.DateField()),
                ("cinema_id", models.CharField(blank=True, max_length=32)),
                ("cinema_name", models.CharField(max_length=200)),
                ("normalized_cinema_name", models.CharField(max_length=200)),
                ("booking_url", models.URLField(blank=True, max_length=1000)),
                ("singleton_slot", models.BooleanField(default=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MONITORING", "监控中"),
                            ("PAUSED", "已暂停"),
                            ("DETECTED", "已检测开票"),
                            ("COMPLETED", "已完成"),
                            ("EXPIRED", "已过期"),
                            ("CANCELLED", "已取消"),
                            ("ERROR", "异常"),
                        ],
                        default="MONITORING",
                        max_length=16,
                    ),
                ),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=200)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_check_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("detected_at", models.DateTimeField(blank=True, null=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["MONITORING", "PAUSED", "DETECTED", "ERROR"],
                            )
                        ),
                        fields=("singleton_slot",),
                        name="one_unfinished_monitor_task",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CheckRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCEEDED", "成功"),
                            ("TEMPORARY_ERROR", "临时错误"),
                            ("RATE_LIMITED", "限流"),
                            ("STRUCTURE_ERROR", "结构错误"),
                            ("CONFIG_ERROR", "配置错误"),
                        ],
                        max_length=24,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("content_fingerprint", models.CharField(blank=True, max_length=64)),
                ("cinema_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_summary", models.CharField(blank=True, max_length=200)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to="core.monitortask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[("OPENING", "开票"), ("EXPIRY", "到期")], max_length=16
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待发送"),
                            ("SENDING", "发送中"),
                            ("SENT", "成功"),
                            ("FAILED", "失败"),
                            ("PERMANENT_FAILED", "永久失败"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("smtp_response", models.CharField(blank=True, max_length=200)),
                ("last_error", models.CharField(blank=True, max_length=200)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.monitortask",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "notification_type"),
                        name="unique_task_notification_type",
                    )
                ],
            },
        ),
    ]
