# Generated by Django 5.2.17 on 2026-08-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="monitortask",
            name="one_unfinished_monitor_task",
        ),
        migrations.RemoveField(
            model_name="monitortask",
            name="singleton_slot",
        ),
        migrations.AddConstraint(
            model_name="monitortask",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["MONITORING", "PAUSED", "DETECTED", "ERROR"])
                ),
                fields=("city_id", "movie_id", "show_date", "normalized_cinema_name"),
                name="one_unfinished_task_per_target",
            ),
        ),
    ]
