# Generated by Django 5.2.17 on 2026-08-17 08:10

from django.db import migrations, models


def copy_recipient_from_smtp(apps, schema_editor):
    SMTPConfig = apps.get_model("core", "SMTPConfig")
    AgentMailConfig = apps.get_model("core", "AgentMailConfig")
    smtp = SMTPConfig.objects.filter(pk=1).first()
    AgentMailConfig.objects.update_or_create(
        pk=1,
        defaults={"recipient_email": smtp.recipient_email if smtp else ""},
    )


def remove_agent_mail_config(apps, schema_editor):
    apps.get_model("core", "AgentMailConfig").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_allow_multiple_monitor_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMailConfig",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        default="mijiatong@agent.qq.com", editable=False, max_length=254
                    ),
                ),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(copy_recipient_from_smtp, remove_agent_mail_config),
    ]
