# Generated by Django 5.2.17 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0005_server_runtime_fields")]

    operations = [
        migrations.AddField(
            model_name="monitortask",
            name="consecutive_terminal_failures",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
