# Generated by Django 5.2.17 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0006_terminal_failure_streak")]

    operations = [
        migrations.CreateModel(
            name="RuntimeState",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("worker_started_at", models.DateTimeField(blank=True, null=True)),
                ("worker_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("last_backup_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_backup_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={"abstract": False},
        ),
    ]
