# Generated by Django 5.2.17 on 2026-08-18

from django.db import migrations, models


def forwards(apps, schema_editor):
    config_model = apps.get_model("core", "AgentMailConfig")
    config_model.objects.filter(is_verified=True).update(verification_status="VERIFIED")
    config_model.objects.filter(is_verified=False).update(verification_status="FAILED")


def backwards(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [("core", "0007_runtime_state")]

    operations = [
        migrations.AddField(
            model_name="agentmailconfig",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "等待 Worker 验证"),
                    ("VERIFIED", "已验证"),
                    ("FAILED", "验证失败"),
                ],
                default="FAILED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="agentmailconfig",
            name="verification_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentmailconfig",
            name="verification_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentmailconfig",
            name="verification_claim_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentmailconfig",
            name="verification_claim_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(forwards, backwards),
    ]
